### ISSUE TITLE
Can we please have an option to remove the console.logs for "complex" parameters

### ISSUE THREAD

**Issue by koscik** [paucls/jasmine-parameterized#2]
The library is great. Thank you for that!

I just have one issue with it. Sometimes the `{}` object is a valid test case. Could we please not log them in console, or at least have an option to disable such logs?

**Comment by paucls** [comment]
I've made the library not log empty objects as part of https://github.com/paucls/jasmine-parameterized/pull/3/files

**Comment by paucls** [comment]
thanks for your feedback, I will publish new version soon

**Comment by paucls** [comment]
new version is 0.5.0 https://www.npmjs.com/package/jasmine-parameterized
