### ISSUE TITLE
null parameter causes test to fail with an exception - paramIsANonEmptyObject

### ISSUE THREAD

**Issue by koscik** [paucls/jasmine-parameterized#4]
The bug was introduced with the 0.5.0 version. Inside `paramIsANonEmptyObject` function, there's a check 
```
typeof this.parameter === 'object' 
```

This condition is satisfied by `null`. Right after this there's a line
```
Object.keys(this.parameter)
```

Which throws an exception if `null` is passed.

Can we maybe get rid of `console.log` altogether? It doesn't seem to bring anything and (In my project) anything can be a valid case - `null`, `undefined`, `{}` etc.

**Comment by paucls** [comment]
Removing the console log and handling null use case for test names.

New version is 1.0.0
